# Site settings
title: Protfolio of Jakob Hilden
email: jakobhilden@gmail.com
description: My portfolio site
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.jkwebs.de" # the base hostname & protocol for your site
twitter_username: jkwebs
github_username:  jhilden
safe: false

# Build settings
markdown: kramdown

exclude: [sass, Gemfile, Gemfile.lock, README.md, node_modules, config.rb]

sass:
  load_paths:
    - _sass
    - node_modules/foundation-sites/scss/
